name: Build EIA Salt vs Price (Apr–Oct last 10y incl 2025)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 17 * * 4'  # Thursdays 17:30 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check EIA_API_KEY presence
        run: |
          if [ -z "${{ secrets.EIA_API_KEY }}" ]; then
            echo "EIA_API_KEY is NOT set. Add it in Settings → Secrets and variables → Actions."; exit 1
          fi
          echo "EIA_API_KEY is present."

      - name: Locate src
        id: locate
        run: |
          if [ -d src ] && [ -d src/eia_storage_plot ]; then
            SRCDIR="src"
          else
            SRCDIR=$(find . -path "./.github" -prune -o -type d -name "eia_storage_plot" -print | head -n1 | xargs -r dirname | xargs -r dirname)
          fi
          if [ -z "$SRCDIR" ] || [ ! -d "$SRCDIR/eia_storage_plot" ]; then
            echo "ERROR: Could not find src/eia_storage_plot in repo."; exit 1
          fi
          echo "src_path=$SRCDIR" >> $GITHUB_OUTPUT

      - name: Run report (Apr–Oct last 10 years incl. 2025)
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: |
          SRCDIR="${{ steps.locate.outputs.src_path }}"
          export PYTHONPATH="$PYTHONPATH:$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$SRCDIR")"
          python scripts/run_report.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eia-salt-vs-price-outputs
          path: |
            out/**
            docs/plots/salt_vs_henryhub.png
            docs/plots/us_total_vs_henryhub.png

      - name: Commit outputs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/data/merged.csv docs/plots/salt_vs_henryhub.png docs/plots/us_total_vs_henryhub.png || true
          git commit -m "CI: update Apr–Oct last-10y plots (salt + US total; 20% trim; 2025 yellow; last5 annotated) [skip ci]" || echo "No changes to commit"
          git push || true
