name: Build EIA Salt vs Price (Apr–Oct last 10y incl 2025)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 4'  # Thursdays 17:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure EIA_API_KEY is set
        run: |
          if [ -z "${{ secrets.EIA_API_KEY }}" ]; then
            echo "EIA_API_KEY is NOT set. Add it in Settings → Secrets and variables → Actions."
            exit 1
          fi

      - name: Build plots
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: |
          # Ensure PYTHONPATH includes src
          if [ -d src/eia_storage_plot ]; then
            export PYTHONPATH="$PYTHONPATH:$PWD/src"
          else
            LOC=$(find . -type d -name eia_storage_plot | head -n1)
            [ -z "$LOC" ] && { echo "ERROR: src/eia_storage_plot not found"; exit 1; }
            export PYTHONPATH="$PYTHONPATH:$(dirname "$(dirname "$LOC")")"
          fi

          python -c "import os,shutil; from datetime import date; \
from eia_storage_plot.fetch import build_weekly_join; \
from eia_storage_plot.plot import select_apr_oct_last10_including_current, make_scatter_salt_vs_price, make_scatter_us_total_vs_price; \
today=date.today(); start_year=today.year-9; end_year=today.year; \
start=f'{start_year}-04-01'; end=f'{end_year}-10-31'; \
print(f'[runner] Using Apr–Oct last 10 years incl. current: {start} → {end}'); \
df=build_weekly_join(start,end); \
df=select_apr_oct_last10_including_current(df,today=today); \
os.makedirs('out/data',exist_ok=True); os.makedirs('out/plots',exist_ok=True); \
df.to_csv('out/data/merged.csv',index=False); \
salt='out/plots/salt_vs_henryhub.png'; us='out/plots/us_total_vs_henryhub.png'; \
make_scatter_salt_vs_price(df,salt,today=today); make_scatter_us_total_vs_price(df,us,today=today); \
os.makedirs('docs/plots',exist_ok=True); \
shutil.copyfile(salt,'docs/plots/salt_vs_henryhub.png'); \
shutil.copyfile(us,'docs/plots/us_total_vs_henryhub.png'); \
print('[runner] rows plotted:',len(df))"

      - uses: actions/upload-artifact@v4
        with:
          name: eia-salt-vs-price-outputs
          path: |
            out/**
            docs/plots/salt_vs_henryhub.png
            docs/plots/us_total_vs_henryhub.png

      - name: Commit outputs to repo
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git add out/data/merged.csv docs/plots/salt_vs_henryhub.png docs/plots/us_total_vs_henryhub.png || true
          git commit -m "CI: update Apr–Oct last-10y plots (salt + US total; 20% trim; 2025 yellow; last5 annotated) [skip ci]" || true
          git push || true
