name: Build EIA Salt vs Price

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        default: '2024-08-01'
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        default: ''
      all_data:
        description: 'Plot all returned weeks (ignore month filters)? true/false'
        required: false
        default: 'false'
  schedule:
    # Every Thursday at 17:30 UTC (≈ 12:30 p.m. Central during DST)
    - cron: '30 17 * * 4'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (diagnostic)
        run: |
          pwd
          ls -la
          echo "---- up to 3 levels ----"
          find . -maxdepth 3 -type d -print

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (auto-detect requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            REQ=$(find . -maxdepth 4 -type f -name "requirements.txt" | head -n1)
            if [ -z "$REQ" ]; then
              echo "ERROR: requirements.txt not found anywhere in repo"; exit 1
            fi
            echo "Using $REQ"
            pip install -r "$REQ"
          fi

      - name: Check EIA_API_KEY presence
        run: |
          if [ -z "${{ secrets.EIA_API_KEY }}" ]; then
            echo "EIA_API_KEY is NOT set. Add it in Settings → Secrets and variables → Actions."; exit 1
          fi
          echo "EIA_API_KEY is present."

      - name: Locate script and src (auto-detect)
        id: locate
        run: |
          SCRIPT=""
          # Prefer repo-root scripts/run_report.py
          if [ -f scripts/run_report.py ]; then
            SCRIPT="scripts/run_report.py"
          else
            # Search nested locations
            SCRIPT=$(find . -maxdepth 5 -path "*/scripts/run_report.py" | head -n1 || true)
          fi

          if [ -z "$SCRIPT" ]; then
            echo "ERROR: run_report.py not found in repo"; exit 1
          fi

          echo "Found script: $SCRIPT"
          echo "script_path=$SCRIPT" >> $GITHUB_OUTPUT

          # Determine src directory for PYTHONPATH
          SRCDIR1="src"
          SRCDIR2="$(dirname "$SCRIPT")/../src"
          # Prefer repo-root src if present
          if [ -d "$SRCDIR1" ]; then
            SRCDIR="$SRCDIR1"
          elif [ -d "$SRCDIR2" ]; then
            SRCDIR="$SRCDIR2"
          else
            echo "WARNING: src/ not found at repo root or adjacent to the script."
            SRCDIR=""
          fi
          echo "Using SRCDIR: $SRCDIR"
          echo "src_path=$SRCDIR" >> $GITHUB_OUTPUT

      - name: Run report
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: |
          SCRIPT="${{ steps.locate.outputs.script_path }}"
          SRCDIR="${{ steps.locate.outputs.src_path }}"

          # Build PYTHONPATH
          if [ -n "$SRCDIR" ]; then
            export PYTHONPATH="$PYTHONPATH:$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$SRCDIR")"
          fi

          START="${{ github.event.inputs.start_date }}"
          END="${{ github.event.inputs.end_date }}"
          ALL="${{ github.event.inputs.all_data }}"
          if [ -z "$START" ]; then START="2024-08-01"; fi

          if [ "$ALL" = "true" ]; then
            python "$SCRIPT" --start "$START" ${END:+--end "$END"} --all-data
          else
            python "$SCRIPT" --start "$START" ${END:+--end "$END"}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eia-salt-vs-price-outputs
          path: |
            out/**
            docs/plots/salt_vs_henryhub.png

      - name: Commit outputs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/data/merged.csv docs/plots/salt_vs_henryhub.png || true
          git commit -m "CI: update data and plot [skip ci]" || echo "No changes to commit"
          git push || true
