name: Build EIA Salt vs Price (Apr–Oct last 5y incl 2025)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 4'  # Thursdays 17:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Verify EIA_API_KEY
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: test -n "$EIA_API_KEY" || (echo "EIA_API_KEY is NOT set (Settings → Secrets and variables → Actions)" >&2; exit 1)

      - name: Run report
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: python scripts/run_report.py

      - uses: actions/upload-artifact@v4
        with:
          name: eia-salt-vs-price-outputs
          path: |
            out/**
            docs/plots/salt_vs_henryhub.png
            docs/plots/us_total_vs_henryhub.png

      - name: Commit outputs
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git add out/data/merged.csv docs/plots/salt_vs_henryhub.png docs/plots/us_total_vs_henryhub.png || true
          git commit -m "CI: update Apr–Oct last-5y plots (salt + US total; 20% trim; 2025 yellow; last5 annotated) [skip ci]" || true
          git push || true
