name: Build EIA Salt vs Price

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        default: '2024-08-01'
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        default: ''
      all_data:
        description: 'Plot all returned weeks (ignore month filters)? true/false'
        required: false
        default: 'false'
  schedule:
    # Every Thursday at 17:30 UTC (≈ 12:30 p.m. Central during DST)
    - cron: '30 17 * * 4'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (diagnostic)
        run: |
          pwd
          ls -la
          echo "---- up to 3 levels ----"
          find . -maxdepth 3 -type d -print
          echo "---- any run_report.py? ----"
          find . -maxdepth 5 -type f -name "run_report.py" -print

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check EIA_API_KEY presence
        run: |
          if [ -z "${{ secrets.EIA_API_KEY }}" ]; then
            echo "EIA_API_KEY is NOT set. Add it in Settings → Secrets and variables → Actions."
            exit 1
          else
            echo "EIA_API_KEY is present."
          fi

      - name: Validate expected files exist
        run: |
          test -f scripts/run_report.py || { echo "ERROR: scripts/run_report.py missing at repo root"; exit 1; }
          test -f requirements.txt || { echo "ERROR: requirements.txt missing at repo root"; exit 1; }
          test -f src/eia_storage_plot/fetch.py || { echo "ERROR: src/eia_storage_plot/fetch.py missing"; exit 1; }
          test -f src/eia_storage_plot/plot.py || { echo "ERROR: src/eia_storage_plot/plot.py missing"; exit 1; }

      - name: Run report
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          START="${{ github.event.inputs.start_date }}"
          END="${{ github.event.inputs.end_date }}"
          ALL="${{ github.event.inputs.all_data }}"
          if [ -z "$START" ]; then START="2024-08-01"; fi
          if [ "$ALL" = "true" ]; then
            python scripts/run_report.py --start "$START" ${END:+--end "$END"} --all-data
          else
            python scripts/run_report.py --start "$START" ${END:+--end "$END"}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eia-salt-vs-price-outputs
          path: |
            out/**
            docs/plots/salt_vs_henryhub.png

      - name: Commit outputs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/data/merged.csv docs/plots/salt_vs_henryhub.png || true
          git commit -m "CI: update data and plot [skip ci]" || echo "No changes to commit"
          git push || true
